version: "3.10"

services:
  plants-database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=plants
      - POSTGRES_USER=plants
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
  plants-database-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"